
# 1. Find the total sales revenue generated by each employee.


# 2. Retrieve the top 5 customers with the highest credit limits.


# 3. List the products with their categories and the total quantity available in each warehouse.


# 4. Find the customers information of those who have had their orders Canceled or their order 
#	 status is Pending


# 5. Calculate the average standard cost and list price for each product category.


# 6. Retrieve the top 3 best-selling products in terms of total quantity sold.


# 7. Find the customers who have placed orders for products from more than two different 
#	 categories.


# 8. List the sales revenue generated by each product category in descending order.


# 9. Retrieve the employees who have not been assigned as managers to any other employee.


# 10. Calculate the average credit limit for customers in each region.




